#!/bin/zsh

# This is the wrapper for mlir-opt-like programs.
# See also pygmentize_mlir, which can be used separately.

# function wrap_mlir_opt() {
if ! [ -t 1 ] || ! zstyle -T ':plugins:mlir:pygments' enabled || (($@[(I)--help*])); then
  command "$@"
else 
  # Add some arguments to not break terminal when dealing with large constants
  local args=($@)
  if ! (($args[(I)--mlir-elide-resource-strings-if-larger*])); then
    args+=(--mlir-elide-resource-strings-if-larger 60)
  fi
  if ! (($args[(I)--mlir-elide-elementsattrs-if-larger*])); then
    args+=(--mlir-elide-elementsattrs-if-larger 60)
  fi

  command "${args[@]}" | pygmentize_mlir
fi
# }
